RECHARGE_CERT_ROOT_DIR = '/Users/misaka/Desktop/workspace_fn/dispatching_api/upload/recharge_certs'
RECHARGE_CERT_ROOT_URL = 'http://localhost:8001/cert'
QRCODE_ROOT_DIR = '/Users/misaka/Desktop/workspace_fn/dispatching_api/upload/agent_qrcode'
QRCODE_ROOT_URL = 'http://localhost:8001/qrcode'
CUSTOMER_QRCODE_ROOT_DIR = '/Users/misaka/Desktop/workspace_fn/dispatching_api/upload/customer_qrcode'
CUSTOMER_QRCODE_ROOT_URL = 'http://localhost:8001/customer-qrcode'
